### ISSUE TITLE
Repository for the VSCode extension does not exist.

### ISSUE THREAD

**Issue by aadrian** [Aeraphe/xvba-cli#1]
Hi,

The repository mentioned in the VSCode extension page :
https://marketplace.visualstudio.com/items?itemName=local-smart.excel-live-server

does not seem to exist (it points to an non-nexisting repo https://github.com/aeraphe/excel-autoload  )

Thank you.

**Comment by Aeraphe** [comment]
This repository is private yet

Thank you for feedback!
